// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjf1wRRWgr_t2YpELPVTquiCqzm5zCrGk',
    appId: '1:1021837806965:web:78ac0a1beb719da782973c',
    messagingSenderId: '1021837806965',
    projectId: 'flutter-day-46',
    authDomain: 'flutter-day-46.firebaseapp.com',
    storageBucket: 'flutter-day-46.appspot.com',
    measurementId: 'G-18JY5F18DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMqnDSJDVS7h9orlyCJEbNGvyoEdBdh8',
    appId: '1:1021837806965:android:b7344533f2db033e82973c',
    messagingSenderId: '1021837806965',
    projectId: 'flutter-day-46',
    storageBucket: 'flutter-day-46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1GEiXVJIbEoLOfNFMmGoS476KTLQK7A',
    appId: '1:1021837806965:ios:248f1994c6e3137d82973c',
    messagingSenderId: '1021837806965',
    projectId: 'flutter-day-46',
    storageBucket: 'flutter-day-46.appspot.com',
    iosBundleId: 'com.example.flutterDay50',
  );
}
